TA-247 Respondent Nightly setup
hmcts/div-respondent-frontend pull request #499
Opened 2020-11-17 12:04 UTC by phaniperla

# Description

Respondent nightly Pipeline setup

https://tools.hmcts.net/jira/browse/TA-247

2020-11-17 13:19 UTC, mounikahmcts approved these changes

2020-11-17 14:38 UTC, Rob-Doherty requested changes

2020-11-17 14:38 UTC, Rob-Doherty commented on Jenkinsfile_nightly
> +  ])
Why do you want to run the nightly jobs at 2pm?

2020-11-17 14:38 UTC, Rob-Doherty commented on Jenkinsfile_nightly
> +  loadVaultSecrets(secrets)
the vault secrets are needed in the `CrossBrowserTests`, so I think this should go back to the top of the test steps like it was originally:
```
    loadVaultSecrets(secrets)
    enableCrossBrowserTest()
    enableSecurityScan()
```

2020-11-17 16:31 UTC, phaniperla commented on Jenkinsfile_nightly
> +  ])
When do you want me schedule  the corn job, 

updated corn job at 21:00

2020-11-17 16:31 UTC, phaniperla commented on Jenkinsfile_nightly
> +  loadVaultSecrets(secrets)
updated

2020-11-18 09:32 UTC, phaniperla reviewed
Addressed reviewer comments

2020-11-18 10:10 UTC, Rob-Doherty approved these changes
looks good to me 👍

2020-11-18 10:10 UTC, Rob-Doherty commented on package.json
> +    "test:fullfunctional": "NODE_PATH=. LOG_LEVEL=DEBUG codeceptjs run-multiple parallel -c test/e2e/codecept.conf.js --steps --grep '@Pipeline' --reporter mocha-multi",
nice! 👌

2020-11-18 10:19 UTC, phaniperla commented on package.json
> +    "test:fullfunctional": "NODE_PATH=. LOG_LEVEL=DEBUG codeceptjs run-multiple parallel -c test/e2e/codecept.conf.js --steps --grep '@Pipeline' --reporter mocha-multi",
Thank you

2020-11-18 14:30 UTC, merged