TA-247 Respondent Nightly Pipeline setup
hmcts/div-respondent-frontend pull request #500
Opened 2020-11-19 10:10 UTC by phaniperla

# Description
 Respondent Nightly pipeline build is crashing due to Puppeteer. This PR contains the fix for respondent nightly pipeline

2020-11-23 10:49 UTC, Rob-Doherty requested changes

2020-11-23 10:49 UTC, Rob-Doherty commented on test/e2e/paths/co-respondent/adulteryJourney.js
> +    }
@phaniperla these are the same lines as the previous 4 (lines 51 - 54) - Mariana has already added this for `respondentEquality`. How come you're duplicating it?

2020-11-23 10:49 UTC, Rob-Doherty commented on test/e2e/paths/respondent/2yrSeparationHappyPath-en-cy.js
> +    }
same here

2020-11-23 10:49 UTC, Rob-Doherty commented on test/e2e/paths/respondent/5yrSeparationHappyPath-en-cy.js
> +    }
same here

2020-11-23 10:49 UTC, Rob-Doherty commented on test/e2e/paths/respondent/behaviourHappyPath-en-cy.js
> +    }
same here

2020-11-23 10:49 UTC, Rob-Doherty commented on config/default.yml
> +  nightlyPCQCheck: 'true'
this is already covered by `respondentEquality`

2020-11-23 10:49 UTC, Rob-Doherty commented on Jenkinsfile_nightly
> +//  enableCrossBrowserTest()
please don't merge this in, or all my work will be for nothing! 😄

2020-12-02 07:58 UTC, ruban72 approved these changes

2021-01-06 13:29 UTC, closed without merging