Respondent jurisdiction changes for brexit.
hmcts/div-respondent-frontend pull request #532
Opened 2021-02-10 15:47 UTC by uzairbaig

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

* Hardware:
* O/S and version:
* JDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-02-10 15:48 UTC, TSeelig approved these changes

2021-02-10 15:56 UTC, bendoc1996 approved these changes

2021-03-04 10:50 UTC, johnoneill46 requested changes

2021-03-04 10:50 UTC, johnoneill46 commented on steps/co-respondent/cr-review-application/CrReviewApplication.content.json
> +    "jurisdictionConnectionResDomiciled": "The applicant and respondent are both domiciled in England and Wales.",
Assume this content should be changed?

2021-03-04 10:54 UTC, Cotterale commented on steps/co-respondent/cr-review-application/CrReviewApplication.content.json
> +    "jurisdictionConnectionResDomiciled": "The applicant and respondent are both domiciled in England and Wales.",
Correct, Needs to be changed to:

```json
"jurisdictionConnectionPetDomiciled": "The Petitioner is domiciled in England and Wales",
"jurisdictionConnectionResDomiciled": "The Respondent is domiciled in England and Wales",
```

2021-03-15 15:43 UTC, bendoc1996 commented on steps/co-respondent/cr-review-application/CrReviewApplication.content.json
> +    "jurisdictionConnectionResDomiciled": "The applicant and respondent are both domiciled in England and Wales.",
Was this ever addressed?

2021-03-15 15:44 UTC, bendoc1996 requested changes
Not sure if John and Dale's comments were addressed.

2021-03-15 15:46 UTC, bendoc1996 approved these changes

2021-04-06 07:03 UTC, Cotterale commented
Closing, This was an older PR

2021-04-06 07:03 UTC, closed without merging